### ISSUE TITLE
Label choice per observation

### ISSUE THREAD

**Issue by MaxHalford** [janfreyberg/superintendent#66]
Hey @janfreyberg, I hope this finds you well.

I was wondering if it would be possible to expose a function that allows choosing which labels to display on a per-sample basis. Basically, for each sample, I already can determine a subset of labels to choose by using some side information. Does this make sense?

I guess the API would look like the `display_func` parameter. It could be called `display_labels` or something like that. One could also imagine passing a function to the `labels` parameter instead of just a list.

I would have sent a pull request but I can't quite figure out how to do this; maybe it will be a walk for you!

Kind regards.

**Comment by janfreyberg** [comment]
Hi Max, this is a really nice idea. Could you give a more detailed example of the use case? It almost sounds like these are separate labelling tasks, where you have a subset of your input data being labelled with labels 1-5, and another subset with labels 6-10? Or is it more on an individual basis, where some data points can be 1, 3, 7, others 1, 2, 6, etc?

I like the idea of passing a function for labels, but that also sounds like the most difficult to implement. I think a callback would be easier. It could actually be passed as part of display_func if you define display_func after your widget (since it could access to the state of the widget). But I'm imagining something more like, `on_display`, where you can register callbacks, and that could optionally receive the widget and then manipulate it.

**Comment by MaxHalford** [comment]
In this case you're right, the "label groups" don't overlap with each other. I'll describe my business use case a little bit to motivate the idea:

I work at Alan, an insurance company. We have operators who label documents manually. They assign high-level labels such as "quote", "invoice", etc. I'm building a system to assign more fine-grained labels such as "dental quote", "osteopathy invoice", etc. I don't have a history of these fine-grained labels, which is why I'm using your (awesome) library :). Therefore, when I look at an example, I already know if it's a quote or an invoice because the manual operator did that work for me. 

Obviously I could just use my brain and use the "macro-label" to guide my choice. But, having a system where I can limit the labels to pick from feels less error-prone. Hopefully you agree.

**Comment by janfreyberg** [comment]
Thanks, that makes sense :)

So I think this definitely can work as a callback. However, I'm currently in the process of doing a relatively big refactor where the input widgets get their own library ([`ipyannotations`](https://github.com/janfreyberg/ipyannotations)), and so it might take me a while to implement this.

I could make an example of how to do this in a slightly hacky way if you need this quickly, though?

**Comment by MaxHalford** [comment]
That would be great!

**Comment by janfreyberg** [comment]
```python
import superintendent

data = [{'type': 'quote 1', 'content': 'this is a quote of type 1 so options a, b, and c should be visible'},
        {'type': 'quote 2', 'content': 'this is a quote of type 2 so options d, e, and f should be visible'}] * 5

widget = superintendent.ClassLabeller()

def custom_display_func(data):
    if data['type'] == 'quote 1':
        widget.options = ['a', 'b', 'c']
    elif data['type'] == 'quote 2':
        widget.options = ['d', 'e', 'f']
    print(data['content'])

widget._display_func = custom_display_func

widget.add_features(data)

widget
```

This produces something along these lines:

![image](https://user-images.githubusercontent.com/4092425/110214539-f841ec80-7e9c-11eb-85eb-fc90ead0838d.png)

**Comment by MaxHalford** [comment]
You're the man :). Have a great weekend!
